### PR TITLE
Add css customization file

### PR DESCRIPTION
**Pull request by rsommerard**
Add a `custom.css.html` import in the `index.html` page and describe how a user can customize the default theme in the `README.md`

This give the ability to the user to easily customize the default theme without changing the original theme files.

What do you think ? 😃

### CODE REVIEW

**Comment by jhabdas** [comment]
@rsommerard Thank you very much this should be great for theme extensibility. The intent of "critical-custom" was for hackcss overrides so it makes sense to add another file for theme overrides. I wonder if we could change the name of the file to "critical-user" so it's more clear the intent of the file is for non-external STYLE blocks intended for User-land? Good for merge with change. Thanks for the addition and happy holidays! 🎅🏼

**Comment by jhabdas** [comment]
You know what. Custom is, well, custom. So why name it anything else? :)~

**Comment by jhabdas** [comment]
Unfortunately I have to revert this change as the Hugo parser is throwing gobs of errors without a `custom.css` file:

```
ERROR: 2017/01/21 16:38:47 template.go:139: Unable to render [partials/custom.css theme/partials/custom.css]
```

Because I already include a `custom-critical file by default, I do not see a strong need to add another CSS file to keep things simple, even if it means customizing a theme file.

**Comment by jhabdas** [comment]
@rsommerard I reintegrated your changes and gave you credits in the README. Thanks for making this suggestion. Please rebase against https://github.com/comfusion/after-dark/commit/7a4c1c0f3b4c2dd0002912716358c5003a52430c for the latest, which includes a number of other enhancements for improved layout, SEO and social social sharing. See README for more details.

**Comment by rsommerard** [comment]
Nice work 👍 
Thanks for considering my proposal 😃

**Pull request merged**
