### PR TITLE
Add layout for archive page

### PR DESCRIPTION
**Pull request by vbrandl**
As stated in #15 an archive page is missing. This template is the one used on https://collantes.us.

To create an archive page, one has to create `content/archive.md` with the following content:
```
+++
title = "Archive"
name = "Archive"
url = "/archive/"
menu = "main"
type = "archive"
+++
```

### CODE REVIEW

**Comment by jhabdas** [comment]
@vbrandl awesome! thanks for the pull. will take a look soon! this will make a nice addition to the site given the simple list pagination being used right now.

**Comment by jhabdas** [comment]
@vbrandl would you mind taking a stab at the readme? I won't be too fussy about it. I've been reworking the crap out of it recently so I'll probably pass over the language a few times anyway.

**Comment by jhabdas** [comment]
Okay. I had some time to think about this a little more. The way I would like to see this implemented is using an _archive_ [Content View](https://gohugo.io/templates/views/). Before a pull will be accepted for archives it must also consider the following:

- [ ] Use of the `time` element with ISO 8601 `datetime` attribute ([example](https://github.com/comfusion/after-dark/blob/bc422b6cdbb55ba7f129ad48e904a3cdb43de219/layouts/partials/post/meta.html#L10-L11))
- [ ] Valid Schema Structured data defining relevant attributes of the article ([example](https://github.com/comfusion/after-dark/blob/4eea0836df50815151471cc029b85ad4d83e89b5/layouts/post/single.html#L8))
- [ ] Post reading time and date DRY with the post meta provided in content summaries ([example](https://github.com/comfusion/after-dark/blob/master/layouts/partials/post/meta.html))

**Comment by vbrandl** [comment]
I'll try to implement it that way but it might take a while. I'm pretty new to this kind of web development.
About the 3rd point: Do you think of something like this:
Example

**Comment by jhabdas** [comment]
@vbrandl That would be awesome. I'm a bit tied up right now with... [insert stuff here]. No rush. Absorb the research, utilize [devdocs.io](http://devdocs.io/), and look to create most minimal, robust and artistic implementation you can think of.

> About the 3rd point: Do you think of something like this.

Precisely.

**Comment by vbrandl** [comment]
Implemented third point 
- [x] Post reading time and date in DRY fashion using the same logic provided for post meta in content summaries in lists and singles

**Comment by jhabdas** [comment]
@vbrandl I'm closing this for now. Please feel free to continue working at your own speed and open a PR when you're ready. I've moved the basic requirements into the related issue.

**Pull request closed without merging**
