### PR TITLE
Make it possible to replace the accent color hack.css uses

### PR DESCRIPTION
**Pull request by belak**
You can see #6 for the original discussion. This was just moved to a different branch.

### CODE REVIEW

**Comment by jhabdas** [comment]
I'm planning to use the satelize NPM module to create a microservice to shift the theme colors based on time of day. I'll also look at making the theme a little easier to configure while I'm in there.

**Comment by jhabdas** [comment]
Furthermore, because these changes make configurable an override to the base CSS it's not likely it'll be done this way. FWIW you may want to open a PR against Hack to facilitate customization here, if it makes sense.

**Comment by belak** [comment]
I think mentioning the custom template which is meant to be overridden and giving a small example might be enough since you should be able to override stuff in the same way as what I'm doing.

**Comment by jhabdas** [comment]
Good point. I'll close this and will keep customization and upgradability in mind for next pass at the style goodies. Thanks again for your PRs kind sir.

**Comment by jhabdas** [comment]
@belak theme variants are now a thing. have fun. https://github.com/comfusion/after-dark/commit/473feab7946e5c5ebd562d807e8efcc6d2a24dfe

**Pull request closed without merging**
