### PR TITLE
Make it possible to replace the accent color hack.css uses

### PR DESCRIPTION
**Pull request by belak**
This was originally an experiment, but I'll probably end up using it for my site and I figured it might be useful for other people as well... it makes it possible to replace the pink accent color uses for anchor tags.

If you specify accent_color in the params, that will be used in place of `#ff2e88`, otherwise it will use the original color.

It does mess with syntax highlighting when editing the css template files, but I'm not sure if there's a way around that.

### CODE REVIEW

**Comment by jhabdas** [comment]
Thanks for the PR. I was poking around the forks yesterday and saw that. Even told a friend in jest, as she'd suggested link colors be green. I'll leave this open for now as a reminder to look for a way to make this configurable, but can't promise anything. :)

**Comment by belak** [comment]
As far as I can tell, this does replace all the instances of the previous color with a configurable value... However, I'd be happy to do this differently if there was a chance of it getting merged in, as I'd rather not maintain a fork if possible, especially considering that you're still actively developing this.

**Comment by belak** [comment]
I'm going to close this and reopen it against another branch because I have some other stuff I'd like to mess with on my master branch.

**Comment by jhabdas** [comment]
@belak No problem either way I'm sure this will come in handy for others and helps raise the visibility of the desire so I can look for opportunities to incorporate it later. Remember, you can always override theme files in your base project using Hugo's organization guidelines so you do not have to maintain a fork (if that helps any).

**Comment by jhabdas** [comment]
@belak you may find this useful https://github.com/comfusion/after-dark/blob/master/README.md#configuring-a-theme-variant

**Pull request closed without merging**
