### PR TITLE
Removing the `by` when no author defined

### PR DESCRIPTION
**Pull request by Fastidious**
If `author` is not set in the `config.{toml | yaml}` **and** not set in the frontmatter, the `by` would print (“Published by on…”). This fixes that.

### CODE REVIEW

**Comment by jhabdas** [comment]
I think what you really want is to remove the author entirely because your site is a single author website? If so, my recommendation is to override the `byline.html` partial until authors has been standardized into `data` as [@bep advises](https://discuss.gohugo.io/t/how-to-access-site-params-map-with-a-params-variable/348/14). At that point I can rework the theme for multi-author support without inventing a new way to do things which would cause others to have to later back out of.

To hide author display in the Byline while maintaining Schema Structured Data integrity override add a `/layouts/partials/post/byline.html` to your site, copy the date from the theme file of the same name and replace:

```
  {{ with .Params.author }}
    by <span itemprop="author">{{ index . }}</span>
  {{ else }}
    by <span itemprop="author">{{ .Site.Params.author }}</span>
  {{ end }}
```

With the following:

```
  {{ with .Params.author }}
    <meta itemprop="author" content="{{ index . }}">
  {{ else }}
    <meta itemprop="author" content="{{ .Site.Params.author }}">
  {{ end }}
```

Note I'd considered simply adding a wrapper class around the author stuff so it could be hidden visibly from user agents, but its better force the override in order to put more pressure on a fix for the root problem.

**Comment by jhabdas** [comment]
@Fastidious please be sure to update to the latest `master` before overriding as I've modified the byline to fix a bug in f106c47e72963940a0aa895eeefb36f0f323a147

**Comment by jhabdas** [comment]
@Fastidious I've incorporated your feedback in https://github.com/comfusion/after-dark/commit/a7f7183cb5bf56fee5efc177a4f04f8bc97dfcb8.

**Comment by Fastidious** [comment]
@jhabdas not sure it is working (well, it isn’t for me, locally). Trying to figure out why.

**Pull request closed without merging**
